version: 2
jobs:
  build:
    docker:
      - image: mgdigital/chromaprint-base:latest
    steps:
      - checkout
      - run:
          name: Test
          command: sbt test
      - run:
          name: Package
          command: sbt package
      - persist_to_workspace:
          paths:
            - project/project
            - project/target
            - target
