version: 2.1
jobs:
  build:
    docker:
      - image: mgdigital/chromaprint-base:latest
    steps:
      - checkout
      - run:
          name: Load
          command: sbt reload clean
      - run:
          name: Test
          command: sbt +test
      - run:
          name: Package
          command: sbt +package
      - store_test_results:
          path: /root/project/target/scala-2.12/test-results
      - codecov/upload
      - store_artifacts:
          path: /root/project/target
      - persist_to_workspace:
          root: /root/project
          paths:
            - project/project
            - project/target
            - target
orbs:
  codecov: codecov/codecov@1.0.4
